/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesStoryIdRouteImport } from './routes/stories.$storyId'
import { Route as StoriesStoryIdIndexRouteImport } from './routes/stories.$storyId.index'
import { Route as StoriesStoryIdTimelineRouteImport } from './routes/stories.$storyId.timeline'
import { Route as StoriesStoryIdScenesRouteImport } from './routes/stories.$storyId.scenes'
import { Route as StoriesStoryIdManuscriptRouteImport } from './routes/stories.$storyId.manuscript'
import { Route as StoriesStoryIdGraphRouteImport } from './routes/stories.$storyId.graph'
import { Route as StoriesStoryIdFlagshipRouteImport } from './routes/stories.$storyId.flagship'
import { Route as StoriesStoryIdExportRouteImport } from './routes/stories.$storyId.export'
import { Route as StoriesStoryIdDraftRouteImport } from './routes/stories.$storyId.draft'
import { Route as StoriesStoryIdCollaborationRouteImport } from './routes/stories.$storyId.collaboration'
import { Route as StoriesStoryIdAiRouteImport } from './routes/stories.$storyId.ai'
import { Route as StoriesStoryIdCharactersIndexRouteImport } from './routes/stories.$storyId.characters.index'
import { Route as StoriesStoryIdScenesIdRouteImport } from './routes/stories.$storyId.scenes.$id'
import { Route as StoriesStoryIdDraftSceneIdRouteImport } from './routes/stories.$storyId.draft.$sceneId'
import { Route as StoriesStoryIdCharactersIdRouteImport } from './routes/stories.$storyId.characters.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdRoute = StoriesStoryIdRouteImport.update({
  id: '/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStoryIdIndexRoute = StoriesStoryIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesStoryIdRoute,
} as any)
const StoriesStoryIdTimelineRoute = StoriesStoryIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => StoriesStoryIdRoute,
} as any)
const StoriesStoryIdScenesRoute = StoriesStoryIdScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => StoriesStoryIdRoute,
} as any)
const StoriesStoryIdManuscriptRoute =
  StoriesStoryIdManuscriptRouteImport.update({
    id: '/manuscript',
    path: '/manuscript',
    getParentRoute: () => StoriesStoryIdRoute,
  } as any)
const StoriesStoryIdGraphRoute = StoriesStoryIdGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => StoriesStoryIdRoute,
} as any)
const StoriesStoryIdFlagshipRoute = StoriesStoryIdFlagshipRouteImport.update({
  id: '/flagship',
  path: '/flagship',
  getParentRoute: () => StoriesStoryIdRoute,
} as any)
const StoriesStoryIdExportRoute = StoriesStoryIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => StoriesStoryIdRoute,
} as any)
const StoriesStoryIdDraftRoute = StoriesStoryIdDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => StoriesStoryIdRoute,
} as any)
const StoriesStoryIdCollaborationRoute =
  StoriesStoryIdCollaborationRouteImport.update({
    id: '/collaboration',
    path: '/collaboration',
    getParentRoute: () => StoriesStoryIdRoute,
  } as any)
const StoriesStoryIdAiRoute = StoriesStoryIdAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => StoriesStoryIdRoute,
} as any)
const StoriesStoryIdCharactersIndexRoute =
  StoriesStoryIdCharactersIndexRouteImport.update({
    id: '/characters/',
    path: '/characters/',
    getParentRoute: () => StoriesStoryIdRoute,
  } as any)
const StoriesStoryIdScenesIdRoute = StoriesStoryIdScenesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoriesStoryIdScenesRoute,
} as any)
const StoriesStoryIdDraftSceneIdRoute =
  StoriesStoryIdDraftSceneIdRouteImport.update({
    id: '/$sceneId',
    path: '/$sceneId',
    getParentRoute: () => StoriesStoryIdDraftRoute,
  } as any)
const StoriesStoryIdCharactersIdRoute =
  StoriesStoryIdCharactersIdRouteImport.update({
    id: '/characters/$id',
    path: '/characters/$id',
    getParentRoute: () => StoriesStoryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/welcome': typeof WelcomeRoute
  '/stories/$storyId': typeof StoriesStoryIdRouteWithChildren
  '/stories/$storyId/ai': typeof StoriesStoryIdAiRoute
  '/stories/$storyId/collaboration': typeof StoriesStoryIdCollaborationRoute
  '/stories/$storyId/draft': typeof StoriesStoryIdDraftRouteWithChildren
  '/stories/$storyId/export': typeof StoriesStoryIdExportRoute
  '/stories/$storyId/flagship': typeof StoriesStoryIdFlagshipRoute
  '/stories/$storyId/graph': typeof StoriesStoryIdGraphRoute
  '/stories/$storyId/manuscript': typeof StoriesStoryIdManuscriptRoute
  '/stories/$storyId/scenes': typeof StoriesStoryIdScenesRouteWithChildren
  '/stories/$storyId/timeline': typeof StoriesStoryIdTimelineRoute
  '/stories/$storyId/': typeof StoriesStoryIdIndexRoute
  '/stories/$storyId/characters/$id': typeof StoriesStoryIdCharactersIdRoute
  '/stories/$storyId/draft/$sceneId': typeof StoriesStoryIdDraftSceneIdRoute
  '/stories/$storyId/scenes/$id': typeof StoriesStoryIdScenesIdRoute
  '/stories/$storyId/characters/': typeof StoriesStoryIdCharactersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/welcome': typeof WelcomeRoute
  '/stories/$storyId/ai': typeof StoriesStoryIdAiRoute
  '/stories/$storyId/collaboration': typeof StoriesStoryIdCollaborationRoute
  '/stories/$storyId/draft': typeof StoriesStoryIdDraftRouteWithChildren
  '/stories/$storyId/export': typeof StoriesStoryIdExportRoute
  '/stories/$storyId/flagship': typeof StoriesStoryIdFlagshipRoute
  '/stories/$storyId/graph': typeof StoriesStoryIdGraphRoute
  '/stories/$storyId/manuscript': typeof StoriesStoryIdManuscriptRoute
  '/stories/$storyId/scenes': typeof StoriesStoryIdScenesRouteWithChildren
  '/stories/$storyId/timeline': typeof StoriesStoryIdTimelineRoute
  '/stories/$storyId': typeof StoriesStoryIdIndexRoute
  '/stories/$storyId/characters/$id': typeof StoriesStoryIdCharactersIdRoute
  '/stories/$storyId/draft/$sceneId': typeof StoriesStoryIdDraftSceneIdRoute
  '/stories/$storyId/scenes/$id': typeof StoriesStoryIdScenesIdRoute
  '/stories/$storyId/characters': typeof StoriesStoryIdCharactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRoute
  '/welcome': typeof WelcomeRoute
  '/stories/$storyId': typeof StoriesStoryIdRouteWithChildren
  '/stories/$storyId/ai': typeof StoriesStoryIdAiRoute
  '/stories/$storyId/collaboration': typeof StoriesStoryIdCollaborationRoute
  '/stories/$storyId/draft': typeof StoriesStoryIdDraftRouteWithChildren
  '/stories/$storyId/export': typeof StoriesStoryIdExportRoute
  '/stories/$storyId/flagship': typeof StoriesStoryIdFlagshipRoute
  '/stories/$storyId/graph': typeof StoriesStoryIdGraphRoute
  '/stories/$storyId/manuscript': typeof StoriesStoryIdManuscriptRoute
  '/stories/$storyId/scenes': typeof StoriesStoryIdScenesRouteWithChildren
  '/stories/$storyId/timeline': typeof StoriesStoryIdTimelineRoute
  '/stories/$storyId/': typeof StoriesStoryIdIndexRoute
  '/stories/$storyId/characters/$id': typeof StoriesStoryIdCharactersIdRoute
  '/stories/$storyId/draft/$sceneId': typeof StoriesStoryIdDraftSceneIdRoute
  '/stories/$storyId/scenes/$id': typeof StoriesStoryIdScenesIdRoute
  '/stories/$storyId/characters/': typeof StoriesStoryIdCharactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/templates'
    | '/welcome'
    | '/stories/$storyId'
    | '/stories/$storyId/ai'
    | '/stories/$storyId/collaboration'
    | '/stories/$storyId/draft'
    | '/stories/$storyId/export'
    | '/stories/$storyId/flagship'
    | '/stories/$storyId/graph'
    | '/stories/$storyId/manuscript'
    | '/stories/$storyId/scenes'
    | '/stories/$storyId/timeline'
    | '/stories/$storyId/'
    | '/stories/$storyId/characters/$id'
    | '/stories/$storyId/draft/$sceneId'
    | '/stories/$storyId/scenes/$id'
    | '/stories/$storyId/characters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/templates'
    | '/welcome'
    | '/stories/$storyId/ai'
    | '/stories/$storyId/collaboration'
    | '/stories/$storyId/draft'
    | '/stories/$storyId/export'
    | '/stories/$storyId/flagship'
    | '/stories/$storyId/graph'
    | '/stories/$storyId/manuscript'
    | '/stories/$storyId/scenes'
    | '/stories/$storyId/timeline'
    | '/stories/$storyId'
    | '/stories/$storyId/characters/$id'
    | '/stories/$storyId/draft/$sceneId'
    | '/stories/$storyId/scenes/$id'
    | '/stories/$storyId/characters'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/templates'
    | '/welcome'
    | '/stories/$storyId'
    | '/stories/$storyId/ai'
    | '/stories/$storyId/collaboration'
    | '/stories/$storyId/draft'
    | '/stories/$storyId/export'
    | '/stories/$storyId/flagship'
    | '/stories/$storyId/graph'
    | '/stories/$storyId/manuscript'
    | '/stories/$storyId/scenes'
    | '/stories/$storyId/timeline'
    | '/stories/$storyId/'
    | '/stories/$storyId/characters/$id'
    | '/stories/$storyId/draft/$sceneId'
    | '/stories/$storyId/scenes/$id'
    | '/stories/$storyId/characters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  TemplatesRoute: typeof TemplatesRoute
  WelcomeRoute: typeof WelcomeRoute
  StoriesStoryIdRoute: typeof StoriesStoryIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId': {
      id: '/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof StoriesStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storyId/': {
      id: '/stories/$storyId/'
      path: '/'
      fullPath: '/stories/$storyId/'
      preLoaderRoute: typeof StoriesStoryIdIndexRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/timeline': {
      id: '/stories/$storyId/timeline'
      path: '/timeline'
      fullPath: '/stories/$storyId/timeline'
      preLoaderRoute: typeof StoriesStoryIdTimelineRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/scenes': {
      id: '/stories/$storyId/scenes'
      path: '/scenes'
      fullPath: '/stories/$storyId/scenes'
      preLoaderRoute: typeof StoriesStoryIdScenesRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/manuscript': {
      id: '/stories/$storyId/manuscript'
      path: '/manuscript'
      fullPath: '/stories/$storyId/manuscript'
      preLoaderRoute: typeof StoriesStoryIdManuscriptRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/graph': {
      id: '/stories/$storyId/graph'
      path: '/graph'
      fullPath: '/stories/$storyId/graph'
      preLoaderRoute: typeof StoriesStoryIdGraphRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/flagship': {
      id: '/stories/$storyId/flagship'
      path: '/flagship'
      fullPath: '/stories/$storyId/flagship'
      preLoaderRoute: typeof StoriesStoryIdFlagshipRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/export': {
      id: '/stories/$storyId/export'
      path: '/export'
      fullPath: '/stories/$storyId/export'
      preLoaderRoute: typeof StoriesStoryIdExportRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/draft': {
      id: '/stories/$storyId/draft'
      path: '/draft'
      fullPath: '/stories/$storyId/draft'
      preLoaderRoute: typeof StoriesStoryIdDraftRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/collaboration': {
      id: '/stories/$storyId/collaboration'
      path: '/collaboration'
      fullPath: '/stories/$storyId/collaboration'
      preLoaderRoute: typeof StoriesStoryIdCollaborationRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/ai': {
      id: '/stories/$storyId/ai'
      path: '/ai'
      fullPath: '/stories/$storyId/ai'
      preLoaderRoute: typeof StoriesStoryIdAiRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/characters/': {
      id: '/stories/$storyId/characters/'
      path: '/characters'
      fullPath: '/stories/$storyId/characters/'
      preLoaderRoute: typeof StoriesStoryIdCharactersIndexRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
    '/stories/$storyId/scenes/$id': {
      id: '/stories/$storyId/scenes/$id'
      path: '/$id'
      fullPath: '/stories/$storyId/scenes/$id'
      preLoaderRoute: typeof StoriesStoryIdScenesIdRouteImport
      parentRoute: typeof StoriesStoryIdScenesRoute
    }
    '/stories/$storyId/draft/$sceneId': {
      id: '/stories/$storyId/draft/$sceneId'
      path: '/$sceneId'
      fullPath: '/stories/$storyId/draft/$sceneId'
      preLoaderRoute: typeof StoriesStoryIdDraftSceneIdRouteImport
      parentRoute: typeof StoriesStoryIdDraftRoute
    }
    '/stories/$storyId/characters/$id': {
      id: '/stories/$storyId/characters/$id'
      path: '/characters/$id'
      fullPath: '/stories/$storyId/characters/$id'
      preLoaderRoute: typeof StoriesStoryIdCharactersIdRouteImport
      parentRoute: typeof StoriesStoryIdRoute
    }
  }
}

interface StoriesStoryIdDraftRouteChildren {
  StoriesStoryIdDraftSceneIdRoute: typeof StoriesStoryIdDraftSceneIdRoute
}

const StoriesStoryIdDraftRouteChildren: StoriesStoryIdDraftRouteChildren = {
  StoriesStoryIdDraftSceneIdRoute: StoriesStoryIdDraftSceneIdRoute,
}

const StoriesStoryIdDraftRouteWithChildren =
  StoriesStoryIdDraftRoute._addFileChildren(StoriesStoryIdDraftRouteChildren)

interface StoriesStoryIdScenesRouteChildren {
  StoriesStoryIdScenesIdRoute: typeof StoriesStoryIdScenesIdRoute
}

const StoriesStoryIdScenesRouteChildren: StoriesStoryIdScenesRouteChildren = {
  StoriesStoryIdScenesIdRoute: StoriesStoryIdScenesIdRoute,
}

const StoriesStoryIdScenesRouteWithChildren =
  StoriesStoryIdScenesRoute._addFileChildren(StoriesStoryIdScenesRouteChildren)

interface StoriesStoryIdRouteChildren {
  StoriesStoryIdAiRoute: typeof StoriesStoryIdAiRoute
  StoriesStoryIdCollaborationRoute: typeof StoriesStoryIdCollaborationRoute
  StoriesStoryIdDraftRoute: typeof StoriesStoryIdDraftRouteWithChildren
  StoriesStoryIdExportRoute: typeof StoriesStoryIdExportRoute
  StoriesStoryIdFlagshipRoute: typeof StoriesStoryIdFlagshipRoute
  StoriesStoryIdGraphRoute: typeof StoriesStoryIdGraphRoute
  StoriesStoryIdManuscriptRoute: typeof StoriesStoryIdManuscriptRoute
  StoriesStoryIdScenesRoute: typeof StoriesStoryIdScenesRouteWithChildren
  StoriesStoryIdTimelineRoute: typeof StoriesStoryIdTimelineRoute
  StoriesStoryIdIndexRoute: typeof StoriesStoryIdIndexRoute
  StoriesStoryIdCharactersIdRoute: typeof StoriesStoryIdCharactersIdRoute
  StoriesStoryIdCharactersIndexRoute: typeof StoriesStoryIdCharactersIndexRoute
}

const StoriesStoryIdRouteChildren: StoriesStoryIdRouteChildren = {
  StoriesStoryIdAiRoute: StoriesStoryIdAiRoute,
  StoriesStoryIdCollaborationRoute: StoriesStoryIdCollaborationRoute,
  StoriesStoryIdDraftRoute: StoriesStoryIdDraftRouteWithChildren,
  StoriesStoryIdExportRoute: StoriesStoryIdExportRoute,
  StoriesStoryIdFlagshipRoute: StoriesStoryIdFlagshipRoute,
  StoriesStoryIdGraphRoute: StoriesStoryIdGraphRoute,
  StoriesStoryIdManuscriptRoute: StoriesStoryIdManuscriptRoute,
  StoriesStoryIdScenesRoute: StoriesStoryIdScenesRouteWithChildren,
  StoriesStoryIdTimelineRoute: StoriesStoryIdTimelineRoute,
  StoriesStoryIdIndexRoute: StoriesStoryIdIndexRoute,
  StoriesStoryIdCharactersIdRoute: StoriesStoryIdCharactersIdRoute,
  StoriesStoryIdCharactersIndexRoute: StoriesStoryIdCharactersIndexRoute,
}

const StoriesStoryIdRouteWithChildren = StoriesStoryIdRoute._addFileChildren(
  StoriesStoryIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  TemplatesRoute: TemplatesRoute,
  WelcomeRoute: WelcomeRoute,
  StoriesStoryIdRoute: StoriesStoryIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
