"""add cascade deletes and check constraints

Revision ID: 1b108e8bdf9b
Revises: ad2d3c4888e2
Create Date: 2026-04-20 17:04:32.307027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b108e8bdf9b'
down_revision: Union[str, None] = 'ad2d3c4888e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('activity_events_story_id_fkey'), 'activity_events', type_='foreignkey')
    op.drop_constraint(op.f('activity_events_user_id_fkey'), 'activity_events', type_='foreignkey')
    op.create_foreign_key(None, 'activity_events', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activity_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('character_edges_story_id_fkey'), 'character_edges', type_='foreignkey')
    op.drop_constraint(op.f('character_edges_source_node_id_fkey'), 'character_edges', type_='foreignkey')
    op.drop_constraint(op.f('character_edges_target_node_id_fkey'), 'character_edges', type_='foreignkey')
    op.create_foreign_key(None, 'character_edges', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'character_edges', 'character_nodes', ['target_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'character_edges', 'character_nodes', ['source_node_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('character_nodes_character_id_fkey'), 'character_nodes', type_='foreignkey')
    op.drop_constraint(op.f('character_nodes_story_id_fkey'), 'character_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'character_nodes', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'character_nodes', 'characters', ['character_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('characters_story_id_fkey'), 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('collaborators_story_id_fkey'), 'collaborators', type_='foreignkey')
    op.drop_constraint(op.f('collaborators_user_id_fkey'), 'collaborators', type_='foreignkey')
    op.create_foreign_key(None, 'collaborators', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'collaborators', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comments_scene_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_story_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'scenes', ['scene_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('core_config_nodes_story_id_fkey'), 'core_config_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'core_config_nodes', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('core_settings_story_id_fkey'), 'core_settings', type_='foreignkey')
    op.create_foreign_key(None, 'core_settings', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('draft_contents_scene_id_fkey'), 'draft_contents', type_='foreignkey')
    op.drop_constraint(op.f('draft_contents_story_id_fkey'), 'draft_contents', type_='foreignkey')
    op.create_foreign_key(None, 'draft_contents', 'scenes', ['scene_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'draft_contents', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('export_jobs_story_id_fkey'), 'export_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'export_jobs', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('insights_story_id_fkey'), 'insights', type_='foreignkey')
    op.create_foreign_key(None, 'insights', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('manuscript_chapters_story_id_fkey'), 'manuscript_chapters', type_='foreignkey')
    op.create_foreign_key(None, 'manuscript_chapters', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('memberships_user_id_fkey'), 'memberships', type_='foreignkey')
    op.drop_constraint(op.f('memberships_org_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'memberships', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('scenes_story_id_fkey'), 'scenes', type_='foreignkey')
    op.create_foreign_key(None, 'scenes', 'stories', ['story_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_active_org_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['active_org_id'], ['id'], ondelete='SET NULL')

    # CHECK constraints (not auto-detected by Alembic)
    op.create_check_constraint('ck_scene_tension', 'scenes', 'tension >= 1 AND tension <= 10')
    op.create_check_constraint('ck_scene_act', 'scenes', 'act >= 1')
    op.create_check_constraint('ck_story_target_words', 'stories', 'target_words > 0')
    op.create_check_constraint('ck_story_draft_number', 'stories', 'draft_number >= 0')
    op.create_check_constraint('ck_character_scene_count', 'characters', 'scene_count >= 0')
    op.create_check_constraint('ck_character_longest_gap', 'characters', 'longest_gap >= 0')
    op.create_check_constraint('ck_edge_weight', 'character_edges', 'weight >= 0 AND weight <= 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_active_org_id_fkey'), 'users', 'organizations', ['active_org_id'], ['id'])
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.create_foreign_key(op.f('scenes_story_id_fkey'), 'scenes', 'stories', ['story_id'], ['id'])
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_org_id_fkey'), 'memberships', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(op.f('memberships_user_id_fkey'), 'memberships', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'manuscript_chapters', type_='foreignkey')
    op.create_foreign_key(op.f('manuscript_chapters_story_id_fkey'), 'manuscript_chapters', 'stories', ['story_id'], ['id'])
    op.drop_constraint(None, 'insights', type_='foreignkey')
    op.create_foreign_key(op.f('insights_story_id_fkey'), 'insights', 'stories', ['story_id'], ['id'])
    op.drop_constraint(None, 'export_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('export_jobs_story_id_fkey'), 'export_jobs', 'stories', ['story_id'], ['id'])
    op.drop_constraint(None, 'draft_contents', type_='foreignkey')
    op.drop_constraint(None, 'draft_contents', type_='foreignkey')
    op.create_foreign_key(op.f('draft_contents_story_id_fkey'), 'draft_contents', 'stories', ['story_id'], ['id'])
    op.create_foreign_key(op.f('draft_contents_scene_id_fkey'), 'draft_contents', 'scenes', ['scene_id'], ['id'])
    op.drop_constraint(None, 'core_settings', type_='foreignkey')
    op.create_foreign_key(op.f('core_settings_story_id_fkey'), 'core_settings', 'stories', ['story_id'], ['id'])
    op.drop_constraint(None, 'core_config_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('core_config_nodes_story_id_fkey'), 'core_config_nodes', 'stories', ['story_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_story_id_fkey'), 'comments', 'stories', ['story_id'], ['id'])
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('comments_scene_id_fkey'), 'comments', 'scenes', ['scene_id'], ['id'])
    op.drop_constraint(None, 'collaborators', type_='foreignkey')
    op.drop_constraint(None, 'collaborators', type_='foreignkey')
    op.create_foreign_key(op.f('collaborators_user_id_fkey'), 'collaborators', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('collaborators_story_id_fkey'), 'collaborators', 'stories', ['story_id'], ['id'])
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key(op.f('characters_story_id_fkey'), 'characters', 'stories', ['story_id'], ['id'])
    op.drop_constraint(None, 'character_nodes', type_='foreignkey')
    op.drop_constraint(None, 'character_nodes', type_='foreignkey')
    op.create_foreign_key(op.f('character_nodes_story_id_fkey'), 'character_nodes', 'stories', ['story_id'], ['id'])
    op.create_foreign_key(op.f('character_nodes_character_id_fkey'), 'character_nodes', 'characters', ['character_id'], ['id'])
    op.drop_constraint(None, 'character_edges', type_='foreignkey')
    op.drop_constraint(None, 'character_edges', type_='foreignkey')
    op.drop_constraint(None, 'character_edges', type_='foreignkey')
    op.create_foreign_key(op.f('character_edges_target_node_id_fkey'), 'character_edges', 'character_nodes', ['target_node_id'], ['id'])
    op.create_foreign_key(op.f('character_edges_source_node_id_fkey'), 'character_edges', 'character_nodes', ['source_node_id'], ['id'])
    op.create_foreign_key(op.f('character_edges_story_id_fkey'), 'character_edges', 'stories', ['story_id'], ['id'])
    op.drop_constraint(None, 'activity_events', type_='foreignkey')
    op.drop_constraint(None, 'activity_events', type_='foreignkey')
    op.create_foreign_key(op.f('activity_events_user_id_fkey'), 'activity_events', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('activity_events_story_id_fkey'), 'activity_events', 'stories', ['story_id'], ['id'])

    # Drop CHECK constraints
    op.drop_constraint('ck_edge_weight', 'character_edges', type_='check')
    op.drop_constraint('ck_character_longest_gap', 'characters', type_='check')
    op.drop_constraint('ck_character_scene_count', 'characters', type_='check')
    op.drop_constraint('ck_story_draft_number', 'stories', type_='check')
    op.drop_constraint('ck_story_target_words', 'stories', type_='check')
    op.drop_constraint('ck_scene_act', 'scenes', type_='check')
    op.drop_constraint('ck_scene_tension', 'scenes', type_='check')
    # ### end Alembic commands ###
